import type {
  RoleModel,
  PermissionCreateInput,
} from "@/generated/prisma/models";
import { PermissionType } from "@/generated/prisma/enums";
const _role: Partial<RoleModel>[] = [
  {
    name: "超级管理员",
    code: "super_admin",
    description: "超级管理员",
    isSystem: true,
  },
  {
    name: "管理员",
    code: "admin",
    description: "管理员",
  },
  {
    name: "用户",
    code: "user",
    description: "用户",
  },
];
const _department = [
  {
    name: "总部",
    description: "总部",
    children: [
      {
        name: "研发部",
        description: "研发部",
      },
      {
        name: "市场部",
        description: "市场部",
      },
      {
        name: "销售部",
        description: "销售部",
      },
      {
        name: "财务部",
        description: "财务部",
      },
      {
        name: "人事部",
        description: "人事部",
      },
      {
        name: "行政部",
        description: "行政部",
      },
      {
        name: "法务部",
        description: "法务部",
      },
      {
        name: "技术部",
        description: "技术部",
      },
      {
        name: "产品部",
        description: "产品部",
      },
      {
        name: "运营部",
        description: "运营部",
      },
      {
        name: "客服部",
        description: "客服部",
      },
    ],
  },
];
const _menu = [
  {
    name: "Dashboard",
    path: "dashboard",
    redirect: "/dashboard/workplace",
    type: "DIRECTORY",
    component: "#",
    sort: 0,
    enabled: true,
    title: "router.dashboard",
    icon: "gauge",
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,
    children: [
      {
        name: "Workplace",
        path: "workplace",
        redirect: null,
        type: "MENU",
        component: "views/Dashboard/Workplace",
        sort: 0,
        enabled: true,
        title: "router.workplace",
        icon: "monitor",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "Analysis",
        path: "analysis",
        redirect: null,
        type: "MENU",
        component: "views/Dashboard/Analysis",
        sort: 1,
        enabled: true,
        title: "router.analysis",
        icon: "chart-column",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
  {
    name: "Authorization",
    path: "authorization",
    redirect: "/authorization/user",
    type: "DIRECTORY",
    component: "#",
    sort: 1,
    enabled: true,
    title: "router.authorization",
    icon: "lock",
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,

    children: [
      {
        name: "Department",
        path: "department",
        redirect: null,
        type: "MENU",
        component: "views/Authorization/Department/Department",
        sort: 0,
        enabled: true,
        title: "router.department",
        icon: "building-2",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "Dictionary",
        path: "dictionary",
        redirect: null,
        type: "MENU",
        component: "views/Authorization/Dictionary/Dictionary",
        sort: 1,
        enabled: true,
        title: "router.dictionary",
        icon: "book",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "User",
        path: "user",
        redirect: null,
        type: "MENU",
        component: "views/Authorization/User/User",
        sort: 2,
        enabled: true,
        title: "router.userIdentity",
        icon: "user",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "Menu",
        path: "menu",
        redirect: null,
        type: "MENU",
        component: "views/Authorization/Menu/Menu",
        sort: 3,
        enabled: true,
        title: "router.menuManagement",
        icon: "square-menu",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: true,
        noTagsView: false,
      },
      {
        name: "Role",
        path: "role",
        redirect: null,
        type: "MENU",
        component: "views/Authorization/Role/Role",
        sort: 4,
        enabled: true,
        title: "router.role",
        icon: "users-round",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
  {
    name: "Personal",
    path: "personal",
    redirect: "/personal/information",
    type: "DIRECTORY",
    component: "#",
    sort: 2,
    enabled: true,
    title: "router.personalCenter",
    icon: "user",
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,
    children: [
      {
        name: "PersonalCenter",
        path: "information",
        redirect: null,
        type: "MENU",
        component: "views/Personal/PersonalCenter/PersonalCenter",
        sort: 0,
        enabled: true,
        title: "router.userInfo",
        icon: "contact",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "Message",
        path: "message",
        redirect: null,
        type: "MENU",
        component: "views/System/Message/Message",
        sort: 0,
        enabled: true,
        title: "router.message",
        icon: "bell",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
  {
    name: "System",
    path: "system",
    redirect: "/system/userLog",
    type: "DIRECTORY",
    component: "#",
    sort: 3,
    enabled: true,
    title: "router.systemManagement",
    icon: "settings",
    hidden: false,
    affix: false,
    activeMenu: null,
    alwaysShow: false,
    breadcrumb: true,
    canTo: false,
    noCache: false,
    noTagsView: false,
    children: [
      {
        name: "OnlineUser",
        path: "onlineUser",
        redirect: null,
        type: "MENU",
        component: "views/System/OnlineUser/OnlineUser",
        sort: 0,
        enabled: true,
        title: "router.onlineUser",
        icon: "user",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "Oss",
        path: "oss",
        redirect: null,
        type: "MENU",
        component: "views/System/Oss/Oss",
        sort: 0,
        enabled: true,
        title: "router.ossManagement",
        icon: "folder",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "FileList",
        path: "fileList",
        redirect: null,
        type: "MENU",
        component: "views/System/File/FileList",
        sort: 0,
        enabled: true,
        title: "router.fileManagement",
        icon: "file-text",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "Server",
        path: "server",
        redirect: null,
        type: "MENU",
        component: "views/System/Server/Server",
        sort: 0,
        enabled: true,
        title: "router.server",
        icon: "monitor",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "DatabaseBackup",
        path: "databaseBackup",
        redirect: null,
        type: "MENU",
        component: "views/System/DatabaseBackup/DatabaseBackup",
        sort: 0,
        enabled: true,
        title: "router.databaseBackup",
        icon: "database",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "Notification",
        path: "notification",
        redirect: null,
        type: "MENU",
        component: "views/System/Message/Notification",
        sort: 0,
        enabled: true,
        title: "router.notification",
        icon: "mail",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "UserLog",
        path: "userLog",
        redirect: null,
        type: "MENU",
        component: "views/System/UserLog/UserLog",
        sort: 0,
        enabled: true,
        title: "router.userLog",
        icon: "ticket",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
      {
        name: "AuditLog",
        path: "auditLog",
        redirect: null,
        type: "MENU",
        component: "views/System/AuditLog/AuditLog",
        sort: 1,
        enabled: true,
        title: "router.auditLog",
        icon: "shield-cog-corner",
        hidden: false,
        affix: false,
        activeMenu: null,
        alwaysShow: false,
        breadcrumb: true,
        canTo: false,
        noCache: false,
        noTagsView: false,
      },
    ],
  },
];

const _permission: Partial<PermissionCreateInput>[] = [
  {
    name: "新增",
    code: "add",
    resource: "department",
    type: PermissionType.BUTTON,
  },
  {
    name: "编辑",
    code: "update",
    resource: "department",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "department",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "department",
    type: PermissionType.BUTTON,
  },
  {
    name: "新增",
    code: "add",
    resource: "dictionary",
    type: PermissionType.BUTTON,
  },
  {
    name: "编辑",
    code: "update",
    resource: "dictionary",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "dictionary",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "dictionary",
    type: PermissionType.BUTTON,
  },
  {
    name: "新增",
    code: "add",
    resource: "user",
    type: PermissionType.BUTTON,
  },
  {
    name: "编辑",
    code: "update",
    resource: "user",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "user",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "user",
    type: PermissionType.BUTTON,
  },
  {
    name: "新增",
    code: "add",
    resource: "menu",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "menu",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "menu",
    type: PermissionType.BUTTON,
  },
  {
    name: "更新",
    code: "update",
    resource: "menu",
    type: PermissionType.BUTTON,
  },
  {
    name: "新增",
    code: "add",
    resource: "role",
    type: PermissionType.BUTTON,
  },
  {
    name: "编辑",
    code: "update",
    resource: "role",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "role",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "role",
    type: PermissionType.BUTTON,
  },
  {
    name: "新增",
    code: "add",
    resource: "personal",
    type: PermissionType.BUTTON,
  },
  {
    name: "编辑",
    code: "update",
    resource: "personal",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "personal",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "personal",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "fileList",
    type: PermissionType.BUTTON,
  },
  {
    name: "上传",
    code: "add",
    resource: "fileList",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "fileList",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "oss",
    type: PermissionType.BUTTON,
  },
  {
    name: "上传",
    code: "add",
    resource: "oss",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "oss",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "userLog",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "userLog",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "auditLog",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "server",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "databaseBackup",
    type: PermissionType.BUTTON,
  },
  {
    name: "更新配置",
    code: "update",
    resource: "databaseBackup",
    type: PermissionType.BUTTON,
  },
  {
    name: "立即备份",
    code: "run",
    resource: "databaseBackup",
    type: PermissionType.BUTTON,
  },
  {
    name: "下载",
    code: "download",
    resource: "databaseBackup",
    type: PermissionType.BUTTON,
  },
  {
    name: "删除",
    code: "delete",
    resource: "databaseBackup",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "onlineUser",
    type: PermissionType.BUTTON,
  },
  {
    name: "强制下线",
    code: "kick",
    resource: "onlineUser",
    type: PermissionType.BUTTON,
  },
  {
    name: "查看",
    code: "view",
    resource: "message",
    type: PermissionType.BUTTON,
  },
  {
    name: "发送",
    code: "send",
    resource: "notification",
    type: PermissionType.BUTTON,
  },
  //  凡是带有scopeEnabled的权限都要严格对应到后端代码层,细颗粒度的控制无法完全自动,需要代码合并手写控制逻辑
  {
    name: "查看客户",
    code: "view",
    resource: "customer",
    type: PermissionType.API,
    scopeEnabled: true,
  },
  {
    name: "客户详情",
    code: "detail",
    resource: "customer",
    type: PermissionType.API,
    scopeEnabled: true,
  },
  {
    name: "新增",
    code: "add",
    resource: "customer",
    type: PermissionType.BUTTON,
    scopeEnabled: true,
  },
  {
    name: "编辑",
    code: "update",
    resource: "customer",
    type: PermissionType.BUTTON,
    scopeEnabled: true,
  },
  {
    name: "删除",
    code: "delete",
    resource: "customer",
    type: PermissionType.BUTTON,
    scopeEnabled: true,
  },
  {
    name: "导出",
    code: "export",
    resource: "customer",
    type: PermissionType.BUTTON,
    scopeEnabled: true,
  },
  {
    name: "更新高金额客户",
    code: "high-value-update",
    resource: "customer",
    type: PermissionType.API,
    scopeEnabled: false,
  },
  {
    name: "删除已成交客户",
    code: "won-delete",
    resource: "customer",
    type: PermissionType.API,
    scopeEnabled: false,
  },
  {
    name: "查看客户敏感信息",
    code: "sensitive-view",
    resource: "customer",
    type: PermissionType.FIELD,
    scopeEnabled: false,
  },
  {
    name: "更新客户敏感信息",
    code: "sensitive-update",
    resource: "customer",
    type: PermissionType.FIELD,
    scopeEnabled: false,
  },
];

export { _department, _menu, _permission, _role };
