export const AuditAction = {
  AUTH_LOGIN: "auth.login",
  AUTH_LOGIN_FAILED: "auth.login_failed",
  AUTH_LOCKOUT: "auth.lockout",
  AUTH_LOGOUT: "auth.logout",
  AUTH_FORCE_LOGOUT: "auth.force_logout",
  AUTH_REGISTER: "auth.register",
  USER_CREATE: "user.create",
  USER_UPDATE: "user.update",
  USER_DELETE: "user.delete",
  USER_RESET_PASSWORD: "user.reset_password",
  USER_UPDATE_PASSWORD: "user.update_password",
  USER_UPDATE_PROFILE: "user.update_profile",
  ROLE_CREATE: "role.create",
  ROLE_UPDATE: "role.update",
  ROLE_DELETE: "role.delete",
  MENU_CREATE: "menu.create",
  MENU_UPDATE: "menu.update",
  MENU_DELETE: "menu.delete",
  DEPARTMENT_CREATE: "department.create",
  DEPARTMENT_UPDATE: "department.update",
  DEPARTMENT_DELETE: "department.delete",
  CUSTOMER_CREATE: "customer.create",
  CUSTOMER_UPDATE: "customer.update",
  CUSTOMER_DELETE: "customer.delete",
  CUSTOMER_EXPORT: "customer.export",
} as const;

export type AuditActionCode = (typeof AuditAction)[keyof typeof AuditAction];
